config/routes.rb
SampleApp::Application.routes.draw do
  get "users/new"

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get' # As with the other routes, match ’/signup’ gives us the named route signup_path
  match '/help',    to: 'static_pages#help',    via: 'get' 
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }  # before_save is a callback method
  validates(:name,  { presence: true, length: { maximum: 50 }})

  # The application code for email format validation uses a regular expression (or regex) to 
  # define the format, along with the :format argument to the validates method
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i   # the Regex here is a constant (capital letter)
  validates(:email, presence: true, 
  			format: { with: VALID_EMAIL_REGEX }, 
  			uniqueness: { case_sensitive: false })

# has_secure_password gets the password tests (see model/user_spec.rb) to pass
	# Presence validations for the password and its confirmation are automatically added by has_secure_password
	# it also adds 'password' and 'password_confirmation' attributes,
	# requires the presence of the password, requires that they match, 
	# and adds an authenticate method to compare an encrypted password to the password_digest to authenticate users
		# Note: has_secure_password requires a 'password_digest' in your table
  has_secure_password
  validates(:password, { length: { minimum: 6 }})
end


# User.create(name: "John Doe").valid?   => true; this User will be saved into the db
# User.create(name: " ").valid? 		 => false; this User will not be saved into the db

# The following methods trigger validations, and will save the object to the database only if the object is valid:
	
	# create
	# create!
	# save
	# save!
	# update
	# update!

	# The bang versions (e.g. save!) raise an exception if the record is invalid. The non-bang versions don't;
	# save and update return false if the record is invalid;
	# create just returns the object 


# "errors.messages" instance method: 
	# After Active Record has performed validations, any errors found can be 
	# accessed through the errors.messages instance method, which returns a collection of errors. 
	# By definition, an object is valid if this collection is empty after running validations.

	# Note that an object instantiated with 'new' will not report errors even if 
	# it's technically invalid, because validations are not run when using new

	# Examples


=begin 
class Person < ActiveRecord::Base
  validates :name, presence: true
end

$ rails console: 
p = Person.new
=> #<Person id: nil, name: nil>
p.errors.messages
=> {}
 
p.valid?
=> false
p.errors.messages
=> {name:["can't be blank"]}
 
p = Person.create
=> #<Person id: nil, name: nil>
p.errors.messages
=> {name:["can't be blank"]}
=end 



# invalid? is simply the inverse of valid?. 
	# It triggers your validations, returning true if any errors were found in the object, and false otherwise



	# see http://guides.rubyonrails.org/active_record_validations.html

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis. Used in views/application.html.erb (head)
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<%# Here the header tag indicates elements that should go at the top of the page. We’ve given the header tag three CSS classes, called navbar, navbar-fixed-top, and navbar-inverse, separated by spaces %>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
        	<%#  use the Rails helper 'link_to' to create links; the first argument to 'link_to' is the link text, while the second is the URL (can be stubbed with #); The third argument is an 'options hash', in this case adding the CSS id logo to the sample app link. %>	
          <%= link_to "sample app", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Help",    help_path %></li>
              <li><%= link_to "Sign in", '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<%-# following head: the individual :title - as indicated in the indiviual static_page view .erb file - will be yielded, ie. inserted-%>
<head>
<title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

<%- #The effect of following line is to look for a file called app/views/layouts/_shim.html.erb, evaluate its contents, and insert the results into the view (HTML5 for IE < version 9)-%>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
    	<%- # the individual content of this body part is indicated in the individual static_page view .erb files -%>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<%# Rails should call the provide function (method) and associate the string "About Us" with the label (variable) ':title' %>
<%# ':title' is a variable part of the page titles (Home, About Us, etc) %>
<%# The required info on "!Doctype" and "head" are specified in views/layout/application.html.erb; the provide function below just tells the application.html.erb file : for this page yield the title "About Us" %>

<% provide(:title, 'About Us') %>

<%# The following is the individual <body> part of this page, ie here "About us" %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>


<h1>Help</h1>
<p>
   Get help on the Ruby on Rails Tutorial at the
   <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
   To get help on this sample app, see the
   <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>